<?php
namespace ArtiFrame\Cli\Commands;

use ArtiFrame\Cli\Services\Translator;
use ArtiFrame\Cli\Services\Safeguard;

class OptimizeCommand
{
    private Translator $translator;
    private Safeguard  $safeguard;

    public function __construct(Translator $translator)
    {
        $this->translator = $translator;
        $this->safeguard  = new Safeguard($translator);
    }

    public function execute(array $args): void
    {
        $projectRoot = $this->safeguard->getProjectRoot();
        $envPath = $projectRoot . '/.env';
        $cacheDir = $projectRoot . '/config';
        $cachePath = $cacheDir . '/env-cache.php';

        if (!file_exists($envPath)) {
            echo "❌ .env file not found at: {$envPath}\n";
            return;
        }

        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }

        $lines = file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $config = [];

        foreach ($lines as $line) {
            $line = trim($line);
            if (str_starts_with($line, '#')) continue;
            if (!str_contains($line, '=')) continue;

            list($name, $value) = explode('=', $line, 2);
            $name = trim($name);
            $value = trim(trim($value), '"\'');
            
            // Handle booleans
            if (strtolower($value) === 'true') $value = true;
            elseif (strtolower($value) === 'false') $value = false;
            
            $config[$name] = $value;
        }

        $export = var_export($config, true);
        $phpCode = "<?php\n// Auto-generated by artiframe optimize\n// DO NOT EDIT MANUALLY\nreturn {$export};\n";

        file_put_contents($cachePath, $phpCode);

        echo "✅ Environment variables cached successfully at config/env-cache.php\n";
        echo "⚠️  IMPORTANT: Add env-cache.php to your .gitignore if running locally.\n";
    }
}
